version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: realtime_app_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: realtime_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "6432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
